name: telegram_bot
description: A telegram bot for unipi (just CS for now) timetables
version: 1.0.0
repository: https://github.com/UniPi-Orari/telegram-bot

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  televerse: 1.26.1
  intl: ^0.19.0
  unipi_orario_wrapper:
    git:
      url: https://github.com/UniPi-Orari/api-wrapper
      ref: master # branch 
      # ref: ea12e41 # commit hash, comes very handy
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
