name: telegram_bot
description: A telegram bot for unipi (just CS for now) timetables
version: 1.0.0
repository: https://github.com/UniPi-Orari/telegram-bot

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  televerse: 1.26.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
